---
title: "20230927-rent_increases-pdf_reader"
author: "Jared Garfinkel"
date: "`r Sys.Date()`"
output: html_document
---

The histoircal rent increases were found here:  
[https://rentguidelinesboard.cityofnewyork.us/wp-content/uploads/2019/08/aptorders.pdf]

There are more here:

[https://rentguidelinesboard.cityofnewyork.us/wp-content/uploads/2021/07/apartmentchart.pdf]

And here:
[https://rentguidelinesboard.cityofnewyork.us/wp-content/uploads/2022/06/2022-Apartment-Chart.pdf]

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(tesseract)
library(pdftools)
library(magick)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	message = FALSE,
	fig.width = 12, 
  fig.height = 14,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

```{r}
eng = tesseract("eng")
# path = "./data/rent_increases.pdf"
path = "./data/2022-Apartment-Chart.pdf"
images = pdftools::pdf_convert(path, dpi = 250)
```


```{r}
image_proc = function() {
  
  results = 
    # pdftools::pdf_convert(path, dpi = 550) %>%
    magick::image_read(images) %>%
    # image_resize("900") %>% 
    # image_convert(colorspace = "Gray") %>%
    # image_reducenoise() %>%
    # image_trim(fuzz = 40) %>% 
    # tesseract::ocr_data()
    magick::image_ocr_data()
  
  return(results)
}
```

```{r}
result = image_proc()

# The pattern is rent_number, date, "to", date, percent for 1 year increase, percent for 2 year increase.

result2 = result |> 
  mutate(word_number = row_number(),
         # rent_number = as.integer(str_extract(word, "^[:digit:]+")),
         rent_number=as.integer(word),
         date_start = try(mdy(word), silent=TRUE),
         date_end = try(mdy(word), silent=TRUE),
         one_year_raise = if_else(str_detect(word, "%"), str_replace(word, "%", ""), as.character(NA)),
         two_year_raise = if_else(str_detect(word, "%"), str_replace(word, "%", ""), as.character(NA)),
         col1 = case_when(rent_number %in% c(1:54) & !is.na(lead(date_start,1)) ~ lead(date_start, 1)),
         col2 = case_when(rent_number %in% c(1:54) & !is.na(lead(date_end, 3)) ~ lead(date_end, 3)),
         col3 = case_when(rent_number %in% c(1:54) & !is.na(lead(one_year_raise, 4)) ~ lead(one_year_raise, 4)),
         col4 = case_when(rent_number %in% c(1:54) & !is.na(lead(two_year_raise, 5)) ~ as.numeric(lead(two_year_raise, 5)))) |>
  filter(!is.na(rent_number),
         !is.na(col1)) |> 
  select(rent_number, starts_with("col"))
# result |> 
#   filter(word == "32")
# tail(result, 1000)
# result2
# result
  
```

```{r}
result2 |> 
  skimr::skim()
```


```{r}
result2

result2 |> 
  mutate(col3 = as.numeric(col3)) |> 
  reframe(mean_1_year_increase = mean(col3, na.rm=TRUE),
          sd_1_year_increase = sd(col3, na.rm=TRUE),
          mean_2_year_increase = mean(col4, na.rm=TRUE),
          sd_2_year_increase = sd(col4, na.rm=TRUE))

result2 |> 
  # filter(rent_number %in% c(40:54)) |> 
  ggplot(aes(x = col1, y = col4)) +
  geom_point() +
  geom_smooth(se = FALSE) +
  geom_line(aes(x = col1, y = mean(col4, na.rm=TRUE))) +
  geom_label(aes(label = str_sub(col2, start = 1, end = 4)), position = position_jitter(width = 0.4, height = 0.4))

```


